insee:
  communes:
      - uri: "http://id.insee.fr/geo/commune/bc622910-0e35-4b04-aab8-30d3ecf6d013"
        insee_code : "01220"
        label: "Lompnes"
        article_code: "0"
        parent_uri: "http://id.insee.fr/geo/departement/69043f56-a413-47c8-804e-9d9ac0c0b67c"
        start_event_uri: "http://id.insee.fr/geo/evenementGeographique/00000000-0000-0000-0000-000000000000"
        end_event_uri: "http://id.insee.fr/geo/evenementGeographique/2ffc80b6-b246-4d33-b6a9-46b711fe5de0"
        start_date: "1942-01-01"
        end_date: "1942-08-01"
      - uri: "http://id.insee.fr/geo/commune/def17c47-5128-401d-9e42-0690d8c0daae"
        insee_code : "01185"
        label: "Hauteville"
        article_code: "1"
        parent_uri: "http://id.insee.fr/geo/departement/69043f56-a413-47c8-804e-9d9ac0c0b67c"
        start_event_uri: "http://id.insee.fr/geo/evenementGeographique/00000000-0000-0000-0000-000000000000"
        end_event_uri: "http://id.insee.fr/geo/evenementGeographique/2ffc80b6-b246-4d33-b6a9-46b711fe5de0"
        start_date: "1942-01-01"
        end_date: "1942-08-01"
      - uri: "http://id.insee.fr/geo/commune/def17c47-5128-401d-9e42-0690d8c0daae"
        insee_code : "01185"
        label: "Hauteville-Lompnes"
        article_code: "1"
        parent_uri: "http://id.insee.fr/geo/departement/69043f56-a413-47c8-804e-9d9ac0c0b67c|http://id.insee.fr/geo/departement/84680e6f-2e99-44c9-a9ba-2e96a2ae48b7"
        start_event_uri: "http://id.insee.fr/geo/evenementGeographique/2ffc80b6-b246-4d33-b6a9-46b711fe5de0"
        end_event_uri: "http://id.insee.fr/geo/evenementGeographique/6b2f4991-c970-4291-a248-28e6497345a6"
        start_date: "1942-01-01"
        end_date: "2019-01-01"
      - uri: "http://id.insee.fr/geo/commune/76c37d0f-88fd-47b3-9674-000b0e667910"
        insee_code : "54448"
        label: "Regniéville"
        article_code: "0"
        parent_uri: "http://id.insee.fr/geo/departement/b929e329-2989-4408-a7b2-0f7e8cb95cb9"
        start_event_uri: "http://id.insee.fr/geo/evenementGeographique/00000000-0000-0000-0000-000000000000"
        end_event_uri: "http://id.insee.fr/geo/evenementGeographique/6ac12379-99f0-43c6-afe7-83aa0ed22f4b"
        start_date: "1942-01-01"
        end_date: "1942-10-01"
      - uri: "http://id.insee.fr/geo/commune/76c37d0f-88fd-47b3-9674-000b0e667910"
        insee_code : "54518"
        label: "Thiaucourt"
        article_code: "0"
        parent_uri: "http://id.insee.fr/geo/departement/b929e329-2989-4408-a7b2-0f7e8cb95cb9"
        start_event_uri: "http://id.insee.fr/geo/evenementGeographique/00000000-0000-0000-0000-000000000000"
        end_event_uri: "http://id.insee.fr/geo/evenementGeographique/6ac12379-99f0-43c6-afe7-83aa0ed22f4b"
        start_date: "1942-01-01"
        end_date: "1942-10-01"
      - uri: "http://id.insee.fr/geo/commune/5a313706-d371-477c-8ae7-54b397cbad79"
        insee_code : "54518"
        label: "Thiaucourt-Regniéville"
        article_code: "0"
        parent_uri: "http://id.insee.fr/geo/departement/b929e329-2989-4408-a7b2-0f7e8cb95cb9|http://id.insee.fr/geo/departement/761f468e-c041-4626-9b54-524d48de532b"
        start_event_uri: "http://id.insee.fr/geo/evenementGeographique/6ac12379-99f0-43c6-afe7-83aa0ed22f4b"
        end_event_uri: null
        start_date: "1942-10-01"
        end_date: null
      - uri: "http://id.insee.fr/geo/commune/d50ff06d-77a1-42e9-bde5-b2a612b89919"
        insee_code : "54454"
        label: "Remenauville"
        article_code: "0"
        parent_uri: "http://id.insee.fr/geo/departement/b929e329-2989-4408-a7b2-0f7e8cb95cb9"
        start_event_uri: "http://id.insee.fr/geo/evenementGeographique/00000000-0000-0000-0000-000000000000"
        end_event_uri: "http://id.insee.fr/geo/evenementGeographique/5dd8818d-0eb5-4326-866d-99076e689233"
        start_date: "1942-01-01"
        end_date: "1942-10-01"
      - uri: "http://id.insee.fr/geo/commune/4aa381ad-cca4-4ea5-9b86-e0a97547976a"
        insee_code : "54316"
        label: "Limey"
        article_code: "0"
        parent_uri: "http://id.insee.fr/geo/departement/b929e329-2989-4408-a7b2-0f7e8cb95cb9"
        start_event_uri: "http://id.insee.fr/geo/evenementGeographique/5dd8818d-0eb5-4326-866d-99076e689233"
        end_event_uri: null
        start_date: "1942-10-01"
        end_date: null
      - uri: "http://id.insee.fr/geo/commune/700e528a-7267-4bb4-a768-cf1827330385"
        insee_code : "54316"
        label: "Limey-Remenauville"
        article_code: "0"
        parent_uri: "http://id.insee.fr/geo/departement/b929e329-2989-4408-a7b2-0f7e8cb95cb9|http://id.insee.fr/geo/departement/761f468e-c041-4626-9b54-524d48de532b"
        start_event_uri: "http://id.insee.fr/geo/evenementGeographique/00000000-0000-0000-0000-000000000000"
        end_event_uri: "http://id.insee.fr/geo/evenementGeographique/5dd8818d-0eb5-4326-866d-99076e689233"
        start_date: "1942-01-01"
        end_date: "1942-10-01"
      - uri: "http://id.insee.fr/geo/commune/cf2860cc-d888-447d-9465-db009f1f97c7"
        insee_code : "66131"
        label: "Palalda"
        article_code: "0"
        parent_uri: "http://id.insee.fr/geo/departement/85f92734-0bae-4812-b859-9b1d0422aeac"
        start_event_uri: "http://id.insee.fr/geo/evenementGeographique/00000000-0000-0000-0000-000000000000"
        end_event_uri: "http://id.insee.fr/geo/evenementGeographique/065710af-e6d6-4a3d-83d4-b2ce7bbd7b0d"
        start_date: "1942-01-01"
        end_date: "1942-11-01"
      - uri: "http://id.insee.fr/geo/commune/2830f25b-ab37-48f3-8afb-6f20075c613f"
        insee_code : "66003"
        label: "Amélie-les-Bains"
        article_code: "1"
        parent_uri: "http://id.insee.fr/geo/departement/85f92734-0bae-4812-b859-9b1d0422aeac"
        start_event_uri: "http://id.insee.fr/geo/evenementGeographique/00000000-0000-0000-0000-000000000000"
        end_event_uri: "http://id.insee.fr/geo/evenementGeographique/065710af-e6d6-4a3d-83d4-b2ce7bbd7b0d"
        start_date: "1942-01-01"
        end_date: "1942-11-01"
      - uri: "http://id.insee.fr/geo/commune/0cef5f70-b63e-4cee-98a5-b3b7c88234ef"
        insee_code : "66003"
        label: "Amélie-les-Bains-Palalda"
        article_code: "1"
        parent_uri: "http://id.insee.fr/geo/departement/85f92734-0bae-4812-b859-9b1d0422aeac"
        start_event_uri: "http://id.insee.fr/geo/evenementGeographique/065710af-e6d6-4a3d-83d4-b2ce7bbd7b0d"
        end_event_uri: null
        start_date: "1942-11-01"
        end_date: null